"use strict";
// Generated by tools/build_town_assets.py — measured art sizes for the town buildings.
const TOWN_ART = {
 "houses": {
  "groceryStore": {
   "w": 256,
   "h": 144
  },
  "caveEntrance": {
   "w": 64,
   "h": 80
  },
  "cottageLog": {
   "w": 128,
   "h": 144
  },
  "cottagePlaster": {
   "w": 128,
   "h": 144
  },
  "cottageBrick": {
   "w": 128,
   "h": 144
  },
  "guardHouse": {
   "w": 256,
   "h": 144
  },
  "tunnelEntrance": {
   "w": 64,
   "h": 80
  },
  "caveEntranceB": {
   "w": 64,
   "h": 80
  }
 },
 "props": {
  "bldPlanterBox": {
   "w": 28,
   "h": 11
  },
  "bldPlanterBush": {
   "w": 28,
   "h": 17
  },
  "bldBenchWood": {
   "w": 58,
   "h": 18
  },
  "bldBenchStone": {
   "w": 30,
   "h": 12
  },
  "bldLampPost": {
   "w": 9,
   "h": 50
  },
  "bldChimney": {
   "w": 24,
   "h": 57
  }
 },
 "furniture": {
  "bldTableLong": {
   "w": 64,
   "h": 26
  },
  "bldChair": {
   "w": 12,
   "h": 24
  },
  "bldTableRound": {
   "w": 32,
   "h": 35
  },
  "bldStove": {
   "w": 24,
   "h": 63
  },
  "bldStoveBig": {
   "w": 49,
   "h": 63
  },
  "bldWardrobe": {
   "w": 32,
   "h": 58
  },
  "bldDresser": {
   "w": 32,
   "h": 32
  },
  "bldBedSingle": {
   "w": 30,
   "h": 54
  },
  "bldBedDouble": {
   "w": 46,
   "h": 54
  },
  "bldCouch": {
   "w": 43,
   "h": 20
  },
  "bldFireplace": {
   "w": 49,
   "h": 98
  },
  "bldOven": {
   "w": 49,
   "h": 98
  },
  "bldBarrel": {
   "w": 17,
   "h": 24
  },
  "bldChest": {
   "w": 32,
   "h": 32
  },
  "bldCounterSink": {
   "w": 96,
   "h": 31
  },
  "bldBench": {
   "w": 48,
   "h": 20
  },
  "bldTub": {
   "w": 49,
   "h": 27
  },
  "bldPlantFlower": {
   "w": 14,
   "h": 32
  },
  "bldPlantA": {
   "w": 16,
   "h": 21
  },
  "bldPlantB": {
   "w": 16,
   "h": 30
  },
  "bldPlantSmall": {
   "w": 15,
   "h": 24
  },
  "bldTableCloth": {
   "w": 34,
   "h": 29
  },
  "bldChandelier": {
   "w": 27,
   "h": 27
  },
  "bldCuttingBoard": {
   "w": 28,
   "h": 19
  },
  "bldBreadBoard": {
   "w": 30,
   "h": 14
  },
  "bldPot": {
   "w": 12,
   "h": 15
  },
  "bldBasket": {
   "w": 16,
   "h": 16
  },
  "bldKettle": {
   "w": 18,
   "h": 15
  },
  "bldPan": {
   "w": 20,
   "h": 15
  },
  "bldPotionRed": {
   "w": 5,
   "h": 9
  },
  "bldPotionGreen": {
   "w": 5,
   "h": 9
  },
  "bldPotionPurple": {
   "w": 5,
   "h": 9
  },
  "bldBroom": {
   "w": 16,
   "h": 30
  },
  "bldStoolRed": {
   "w": 14,
   "h": 11
  },
  "bldStool": {
   "w": 14,
   "h": 18
  },
  "bldCupboard": {
   "w": 32,
   "h": 26
  },
  "bldCrateDark": {
   "w": 16,
   "h": 23
  },
  "bldWallPanel": {
   "w": 20,
   "h": 19
  },
  "bldWallCandle": {
   "w": 12,
   "h": 16
  },
  "bldShelfLong": {
   "w": 64,
   "h": 40
  },
  "bldCabinetWide": {
   "w": 64,
   "h": 40
  },
  "floorMatBldGreen": {
   "w": 49,
   "h": 48
  },
  "floorMatBldDark": {
   "w": 50,
   "h": 49
  },
  "floorMatBldCross": {
   "w": 80,
   "h": 79
  },
  "bldWallWindow": {
   "w": 26,
   "h": 33
  },
  "bldWallWindowStone": {
   "w": 27,
   "h": 32
  },
  "bldWallFrame": {
   "w": 28,
   "h": 23
  },
  "bldWallBoard": {
   "w": 28,
   "h": 23
  },
  "bldWallTrophyWolf": {
   "w": 16,
   "h": 17
  },
  "bldWallTrophyBear": {
   "w": 16,
   "h": 17
  },
  "bldWallDoorPlank": {
   "w": 20,
   "h": 37
  },
  "bldWallDoorArched": {
   "w": 20,
   "h": 39
  },
  "bldWallShutters": {
   "w": 33,
   "h": 34
  },
  "bldWallCaveHole": {
   "w": 32,
   "h": 40
  }
 },
 "rooms": {
  "cottage_wood": {
   "w": 224,
   "h": 192,
   "cols": 14,
   "rows": 12
  },
  "plaster_room": {
   "w": 224,
   "h": 192,
   "cols": 14,
   "rows": 12
  },
  "guard_room": {
   "w": 320,
   "h": 208,
   "cols": 20,
   "rows": 13
  },
  "cave_room": {
   "w": 352,
   "h": 224,
   "cols": 22,
   "rows": 14
  }
 },
 "wallSets": {
  "log": {
   "band": [
    16,
    88,
    64,
    56
   ],
   "frame": [
    "#000000",
    "#b8976d",
    "#b8976d",
    "#b8976d",
    "#b8976d",
    "#b8976d"
   ]
  },
  "stone": {
   "band": [
    112,
    88,
    64,
    56
   ],
   "frame": [
    "#000000",
    "#000000",
    "#3c3b32",
    "#3c3b32",
    "#3c3b32",
    "#3c3b32"
   ]
  },
  "wood": {
   "band": [
    208,
    88,
    64,
    56
   ],
   "frame": [
    "#000000",
    "#a06131",
    "#7d4c28",
    "#7d4c28",
    "#7d4c28",
    "#7d4c28"
   ]
  },
  "plaster": {
   "band": [
    304,
    88,
    64,
    56
   ],
   "frame": [
    "#000000",
    "#a06131",
    "#7d4c28",
    "#7d4c28",
    "#7d4c28",
    "#7d4c28"
   ]
  }
 },
 "floors": {
  "planks": [
   16,
   322,
   48,
   48
  ],
  "stone": [
   96,
   322,
   48,
   48
  ],
  "herring": [
   176,
   322,
   48,
   48
  ],
  "parquet": [
   264,
   330,
   32,
   32
  ]
 },
 "pc": {
  "pcRocks01": {
   "w": 28,
   "h": 43,
   "group": "Rocks",
   "solid": true
  },
  "pcRocks02": {
   "w": 26,
   "h": 27,
   "group": "Rocks",
   "solid": true
  },
  "pcRocks03": {
   "w": 14,
   "h": 11,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks04": {
   "w": 16,
   "h": 14,
   "group": "Rocks",
   "solid": true
  },
  "pcRocks05": {
   "w": 28,
   "h": 43,
   "group": "Rocks",
   "solid": true
  },
  "pcRocks06": {
   "w": 26,
   "h": 27,
   "group": "Rocks",
   "solid": true
  },
  "pcRocks07": {
   "w": 14,
   "h": 11,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks08": {
   "w": 16,
   "h": 14,
   "group": "Rocks",
   "solid": true
  },
  "pcRocks09": {
   "w": 15,
   "h": 10,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks10": {
   "w": 15,
   "h": 10,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks11": {
   "w": 11,
   "h": 9,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks12": {
   "w": 11,
   "h": 9,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks13": {
   "w": 11,
   "h": 9,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks14": {
   "w": 11,
   "h": 9,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks15": {
   "w": 28,
   "h": 43,
   "group": "Rocks",
   "solid": true
  },
  "pcRocks16": {
   "w": 26,
   "h": 27,
   "group": "Rocks",
   "solid": true
  },
  "pcRocks17": {
   "w": 14,
   "h": 11,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks18": {
   "w": 16,
   "h": 14,
   "group": "Rocks",
   "solid": true
  },
  "pcRocks19": {
   "w": 15,
   "h": 10,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks20": {
   "w": 11,
   "h": 9,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks21": {
   "w": 11,
   "h": 9,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks22": {
   "w": 12,
   "h": 25,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks23": {
   "w": 8,
   "h": 15,
   "group": "Rocks",
   "solid": false
  },
  "pcRocks24": {
   "w": 10,
   "h": 15,
   "group": "Rocks",
   "solid": false
  },
  "pcDungeon01": {
   "w": 14,
   "h": 21,
   "group": "Dungeon",
   "solid": true
  },
  "pcDungeon02": {
   "w": 14,
   "h": 20,
   "group": "Dungeon",
   "solid": true
  },
  "pcDungeon03": {
   "w": 14,
   "h": 20,
   "group": "Dungeon",
   "solid": true
  },
  "pcDungeon04": {
   "w": 54,
   "h": 22,
   "group": "Dungeon",
   "solid": true
  },
  "pcDungeon05": {
   "w": 22,
   "h": 18,
   "group": "Dungeon",
   "solid": true
  },
  "pcDungeon06": {
   "w": 10,
   "h": 21,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon07": {
   "w": 10,
   "h": 22,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon08": {
   "w": 10,
   "h": 20,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon09": {
   "w": 10,
   "h": 14,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon10": {
   "w": 10,
   "h": 19,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon11": {
   "w": 10,
   "h": 14,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon12": {
   "w": 10,
   "h": 15,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon13": {
   "w": 10,
   "h": 18,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon14": {
   "w": 10,
   "h": 21,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon15": {
   "w": 10,
   "h": 21,
   "group": "Dungeon",
   "solid": false
  },
  "pcDungeon16": {
   "w": 10,
   "h": 21,
   "group": "Dungeon",
   "solid": false
  },
  "pcEsoteric01": {
   "w": 12,
   "h": 14,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric02": {
   "w": 11,
   "h": 15,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric03": {
   "w": 17,
   "h": 13,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric04": {
   "w": 11,
   "h": 15,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric05": {
   "w": 17,
   "h": 13,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric06": {
   "w": 11,
   "h": 14,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric07": {
   "w": 13,
   "h": 12,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric08": {
   "w": 13,
   "h": 12,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric09": {
   "w": 11,
   "h": 14,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric10": {
   "w": 11,
   "h": 21,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric11": {
   "w": 11,
   "h": 21,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric12": {
   "w": 9,
   "h": 16,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric13": {
   "w": 9,
   "h": 16,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric14": {
   "w": 9,
   "h": 11,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric15": {
   "w": 12,
   "h": 14,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric16": {
   "w": 13,
   "h": 14,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric17": {
   "w": 9,
   "h": 11,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric18": {
   "w": 9,
   "h": 11,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric19": {
   "w": 16,
   "h": 16,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric20": {
   "w": 9,
   "h": 9,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric21": {
   "w": 9,
   "h": 14,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric22": {
   "w": 15,
   "h": 12,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric23": {
   "w": 14,
   "h": 18,
   "group": "Esoteric",
   "solid": false
  },
  "pcEsoteric24": {
   "w": 9,
   "h": 11,
   "group": "Esoteric",
   "solid": false
  },
  "pcFarm01": {
   "w": 16,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm02": {
   "w": 32,
   "h": 64,
   "group": "Farm",
   "solid": false
  },
  "pcFarm03": {
   "w": 16,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm04": {
   "w": 127,
   "h": 80,
   "group": "Farm",
   "solid": false
  },
  "pcFarm05": {
   "w": 10,
   "h": 17,
   "group": "Farm",
   "solid": false
  },
  "pcFarm06": {
   "w": 15,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm07": {
   "w": 9,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm08": {
   "w": 9,
   "h": 15,
   "group": "Farm",
   "solid": false
  },
  "pcFarm09": {
   "w": 9,
   "h": 9,
   "group": "Farm",
   "solid": false
  },
  "pcFarm10": {
   "w": 16,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm11": {
   "w": 15,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm12": {
   "w": 16,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm13": {
   "w": 24,
   "h": 47,
   "group": "Farm",
   "solid": false
  },
  "pcFarm14": {
   "w": 16,
   "h": 18,
   "group": "Farm",
   "solid": false
  },
  "pcFarm15": {
   "w": 16,
   "h": 18,
   "group": "Farm",
   "solid": false
  },
  "pcFarm16": {
   "w": 15,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm17": {
   "w": 11,
   "h": 14,
   "group": "Farm",
   "solid": false
  },
  "pcFarm18": {
   "w": 11,
   "h": 10,
   "group": "Farm",
   "solid": false
  },
  "pcFarm19": {
   "w": 16,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm20": {
   "w": 11,
   "h": 8,
   "group": "Farm",
   "solid": false
  },
  "pcFarm21": {
   "w": 16,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm22": {
   "w": 48,
   "h": 25,
   "group": "Farm",
   "solid": false
  },
  "pcFarm23": {
   "w": 22,
   "h": 20,
   "group": "Farm",
   "solid": false
  },
  "pcFarm24": {
   "w": 15,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm25": {
   "w": 12,
   "h": 9,
   "group": "Farm",
   "solid": false
  },
  "pcFarm26": {
   "w": 32,
   "h": 13,
   "group": "Farm",
   "solid": false
  },
  "pcFarm27": {
   "w": 11,
   "h": 9,
   "group": "Farm",
   "solid": false
  },
  "pcFarm28": {
   "w": 45,
   "h": 89,
   "group": "Farm",
   "solid": false
  },
  "pcFarm29": {
   "w": 10,
   "h": 8,
   "group": "Farm",
   "solid": false
  },
  "pcFarm30": {
   "w": 16,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm31": {
   "w": 32,
   "h": 26,
   "group": "Farm",
   "solid": false
  },
  "pcFarm32": {
   "w": 15,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm33": {
   "w": 12,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm34": {
   "w": 32,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm35": {
   "w": 12,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm36": {
   "w": 16,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm37": {
   "w": 32,
   "h": 32,
   "group": "Farm",
   "solid": false
  },
  "pcFarm38": {
   "w": 10,
   "h": 8,
   "group": "Farm",
   "solid": false
  },
  "pcFarm39": {
   "w": 16,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm40": {
   "w": 48,
   "h": 26,
   "group": "Farm",
   "solid": false
  },
  "pcFarm41": {
   "w": 15,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm42": {
   "w": 15,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm43": {
   "w": 13,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm44": {
   "w": 16,
   "h": 15,
   "group": "Farm",
   "solid": false
  },
  "pcFarm45": {
   "w": 16,
   "h": 15,
   "group": "Farm",
   "solid": false
  },
  "pcFarm46": {
   "w": 12,
   "h": 10,
   "group": "Farm",
   "solid": false
  },
  "pcFarm47": {
   "w": 16,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm48": {
   "w": 48,
   "h": 59,
   "group": "Farm",
   "solid": false
  },
  "pcFarm49": {
   "w": 45,
   "h": 70,
   "group": "Farm",
   "solid": false
  },
  "pcFarm50": {
   "w": 15,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm51": {
   "w": 13,
   "h": 9,
   "group": "Farm",
   "solid": false
  },
  "pcFarm52": {
   "w": 16,
   "h": 14,
   "group": "Farm",
   "solid": false
  },
  "pcFarm53": {
   "w": 16,
   "h": 14,
   "group": "Farm",
   "solid": false
  },
  "pcFarm54": {
   "w": 14,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm55": {
   "w": 16,
   "h": 12,
   "group": "Farm",
   "solid": false
  },
  "pcFarm56": {
   "w": 10,
   "h": 23,
   "group": "Farm",
   "solid": false
  },
  "pcFarm57": {
   "w": 13,
   "h": 19,
   "group": "Farm",
   "solid": false
  },
  "pcFarm58": {
   "w": 15,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFarm59": {
   "w": 9,
   "h": 9,
   "group": "Farm",
   "solid": false
  },
  "pcFarm60": {
   "w": 16,
   "h": 16,
   "group": "Farm",
   "solid": false
  },
  "pcFurniture01": {
   "w": 10,
   "h": 16,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture02": {
   "w": 14,
   "h": 19,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture03": {
   "w": 14,
   "h": 19,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture04": {
   "w": 80,
   "h": 78,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture05": {
   "w": 12,
   "h": 15,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture06": {
   "w": 12,
   "h": 16,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture07": {
   "w": 12,
   "h": 20,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture08": {
   "w": 12,
   "h": 20,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture09": {
   "w": 48,
   "h": 28,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture10": {
   "w": 12,
   "h": 15,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture11": {
   "w": 12,
   "h": 16,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture12": {
   "w": 48,
   "h": 23,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture13": {
   "w": 10,
   "h": 20,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture14": {
   "w": 96,
   "h": 58,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture15": {
   "w": 14,
   "h": 16,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture16": {
   "w": 10,
   "h": 20,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture17": {
   "w": 14,
   "h": 16,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture18": {
   "w": 14,
   "h": 11,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture19": {
   "w": 80,
   "h": 57,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture20": {
   "w": 32,
   "h": 27,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture21": {
   "w": 8,
   "h": 41,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture22": {
   "w": 26,
   "h": 83,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture23": {
   "w": 32,
   "h": 56,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture24": {
   "w": 63,
   "h": 124,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture25": {
   "w": 64,
   "h": 71,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture26": {
   "w": 22,
   "h": 71,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture27": {
   "w": 20,
   "h": 35,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture28": {
   "w": 28,
   "h": 119,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture29": {
   "w": 22,
   "h": 22,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture30": {
   "w": 24,
   "h": 25,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture31": {
   "w": 30,
   "h": 12,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture32": {
   "w": 64,
   "h": 24,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture33": {
   "w": 30,
   "h": 32,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture34": {
   "w": 28,
   "h": 17,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture35": {
   "w": 28,
   "h": 11,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture36": {
   "w": 30,
   "h": 12,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture37": {
   "w": 8,
   "h": 23,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture38": {
   "w": 12,
   "h": 23,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture39": {
   "w": 58,
   "h": 23,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture40": {
   "w": 74,
   "h": 102,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture41": {
   "w": 58,
   "h": 32,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture42": {
   "w": 27,
   "h": 46,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture43": {
   "w": 14,
   "h": 20,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture44": {
   "w": 21,
   "h": 90,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture45": {
   "w": 44,
   "h": 62,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture46": {
   "w": 9,
   "h": 14,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture47": {
   "w": 12,
   "h": 23,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture48": {
   "w": 11,
   "h": 23,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture49": {
   "w": 16,
   "h": 14,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture50": {
   "w": 44,
   "h": 21,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture51": {
   "w": 80,
   "h": 160,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture52": {
   "w": 28,
   "h": 29,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture53": {
   "w": 29,
   "h": 29,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture54": {
   "w": 10,
   "h": 111,
   "group": "Furniture",
   "solid": false
  },
  "pcFurniture55": {
   "w": 42,
   "h": 111,
   "group": "Furniture",
   "solid": true
  },
  "pcFurniture56": {
   "w": 54,
   "h": 109,
   "group": "Furniture",
   "solid": true
  },
  "pcVegetation01": {
   "w": 29,
   "h": 27,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation02": {
   "w": 29,
   "h": 27,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation03": {
   "w": 29,
   "h": 27,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation04": {
   "w": 29,
   "h": 27,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation05": {
   "w": 9,
   "h": 16,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation06": {
   "w": 11,
   "h": 14,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation07": {
   "w": 13,
   "h": 9,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation08": {
   "w": 11,
   "h": 10,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation09": {
   "w": 42,
   "h": 64,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation10": {
   "w": 42,
   "h": 64,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation11": {
   "w": 42,
   "h": 64,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation12": {
   "w": 42,
   "h": 64,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation13": {
   "w": 34,
   "h": 31,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation14": {
   "w": 43,
   "h": 43,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation15": {
   "w": 43,
   "h": 43,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation16": {
   "w": 43,
   "h": 43,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation17": {
   "w": 43,
   "h": 43,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation18": {
   "w": 39,
   "h": 46,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation19": {
   "w": 12,
   "h": 11,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation20": {
   "w": 10,
   "h": 9,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation21": {
   "w": 16,
   "h": 16,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation22": {
   "w": 31,
   "h": 25,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation23": {
   "w": 11,
   "h": 8,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation24": {
   "w": 32,
   "h": 26,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation25": {
   "w": 15,
   "h": 26,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation26": {
   "w": 11,
   "h": 31,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation27": {
   "w": 9,
   "h": 27,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation28": {
   "w": 11,
   "h": 13,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation29": {
   "w": 9,
   "h": 11,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation30": {
   "w": 12,
   "h": 9,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation31": {
   "w": 14,
   "h": 15,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation32": {
   "w": 9,
   "h": 16,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation33": {
   "w": 8,
   "h": 16,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation34": {
   "w": 16,
   "h": 21,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation35": {
   "w": 10,
   "h": 9,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation36": {
   "w": 31,
   "h": 25,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation37": {
   "w": 11,
   "h": 8,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation38": {
   "w": 32,
   "h": 26,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation39": {
   "w": 15,
   "h": 26,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation40": {
   "w": 11,
   "h": 13,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation41": {
   "w": 9,
   "h": 11,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation42": {
   "w": 12,
   "h": 9,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation43": {
   "w": 14,
   "h": 15,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation44": {
   "w": 9,
   "h": 16,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation45": {
   "w": 16,
   "h": 21,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation46": {
   "w": 10,
   "h": 9,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation47": {
   "w": 31,
   "h": 25,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation48": {
   "w": 11,
   "h": 8,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation49": {
   "w": 32,
   "h": 26,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation50": {
   "w": 15,
   "h": 26,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation51": {
   "w": 11,
   "h": 13,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation52": {
   "w": 9,
   "h": 11,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation53": {
   "w": 12,
   "h": 9,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation54": {
   "w": 14,
   "h": 15,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation55": {
   "w": 9,
   "h": 16,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation56": {
   "w": 14,
   "h": 14,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation57": {
   "w": 13,
   "h": 9,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation58": {
   "w": 11,
   "h": 14,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation59": {
   "w": 11,
   "h": 14,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation60": {
   "w": 16,
   "h": 8,
   "group": "Vegetation",
   "solid": false
  },
  "pcVegetation61": {
   "w": 28,
   "h": 8,
   "group": "Vegetation",
   "solid": false
  },
  "pcResources01": {
   "w": 12,
   "h": 16,
   "group": "Resources",
   "solid": false
  },
  "pcResources02": {
   "w": 14,
   "h": 11,
   "group": "Resources",
   "solid": false
  },
  "pcResources03": {
   "w": 9,
   "h": 10,
   "group": "Resources",
   "solid": false
  },
  "pcResources04": {
   "w": 22,
   "h": 13,
   "group": "Resources",
   "solid": false
  },
  "pcResources05": {
   "w": 15,
   "h": 20,
   "group": "Resources",
   "solid": false
  },
  "pcTree0102": {
   "w": 246,
   "h": 126,
   "group": "Tree",
   "solid": true
  },
  "pcTree0103": {
   "w": 207,
   "h": 192,
   "group": "Tree",
   "solid": true
  },
  "pcTree0104": {
   "w": 355,
   "h": 254,
   "group": "Tree",
   "solid": true
  },
  "pcTree0105": {
   "w": 436,
   "h": 368,
   "group": "Tree",
   "solid": true
  },
  "pcTree0202": {
   "w": 122,
   "h": 95,
   "group": "Tree",
   "solid": true
  },
  "pcTree0203": {
   "w": 135,
   "h": 156,
   "group": "Tree",
   "solid": true
  },
  "pcTree0204": {
   "w": 180,
   "h": 215,
   "group": "Tree",
   "solid": true
  },
  "pcTree0205": {
   "w": 283,
   "h": 317,
   "group": "Tree",
   "solid": true
  },
  "pcTree0302": {
   "w": 125,
   "h": 155,
   "group": "Tree",
   "solid": true
  },
  "pcTree0303": {
   "w": 184,
   "h": 287,
   "group": "Tree",
   "solid": true
  },
  "pcTree0304": {
   "w": 267,
   "h": 416,
   "group": "Tree",
   "solid": true
  },
  "pcTree0305": {
   "w": 369,
   "h": 511,
   "group": "Tree",
   "solid": true
  }
 },
 "wallSets_extra": {
  "cave": {
   "sheet": "cave_sheet",
   "band": [
    0,
    0,
    64,
    56
   ],
   "frame": [
    "#0a0706",
    "#3a281e",
    "#4a3326",
    "#34241b",
    "#1c130e"
   ]
  }
 },
 "floors_extra": {
  "cave": {
   "sheet": "cave_sheet",
   "box": [
    64,
    0,
    48,
    48
   ]
  }
 },
 "caveLayouts": {
  "cave_room": {
   "tiles": [
    "12,8",
    "12,9",
    "12,10",
    "12,11",
    "13,7",
    "13,8",
    "13,9",
    "13,10",
    "13,11",
    "13,12",
    "14,7",
    "14,8",
    "14,9",
    "14,10",
    "14,11",
    "14,12",
    "14,13",
    "14,16",
    "14,17",
    "14,18",
    "14,19",
    "14,20",
    "14,21",
    "14,22",
    "14,23",
    "15,6",
    "15,7",
    "15,8",
    "15,9",
    "15,10",
    "15,11",
    "15,12",
    "15,13",
    "15,14",
    "15,15",
    "15,16",
    "15,17",
    "15,18",
    "15,19",
    "15,20",
    "15,21",
    "15,22",
    "15,23",
    "15,24",
    "16,6",
    "16,7",
    "16,8",
    "16,9",
    "16,10",
    "16,11",
    "16,12",
    "16,13",
    "16,14",
    "16,15",
    "16,16",
    "16,17",
    "16,18",
    "16,19",
    "16,20",
    "16,21",
    "16,22",
    "16,23",
    "16,24",
    "16,25",
    "16,26",
    "17,6",
    "17,7",
    "17,8",
    "17,9",
    "17,10",
    "17,11",
    "17,12",
    "17,13",
    "17,14",
    "17,15",
    "17,16",
    "17,17",
    "17,18",
    "17,19",
    "17,20",
    "17,21",
    "17,22",
    "17,23",
    "17,24",
    "17,25",
    "17,26",
    "17,27",
    "18,6",
    "18,7",
    "18,8",
    "18,9",
    "18,10",
    "18,11",
    "18,12",
    "18,13",
    "18,14",
    "18,15",
    "18,16",
    "18,17",
    "18,18",
    "18,19",
    "18,20",
    "18,21",
    "18,22",
    "18,23",
    "18,24",
    "18,25",
    "18,26",
    "18,27",
    "18,28",
    "19,6",
    "19,7",
    "19,8",
    "19,9",
    "19,10",
    "19,11",
    "19,12",
    "19,13",
    "19,14",
    "19,15",
    "19,16",
    "19,17",
    "19,18",
    "19,19",
    "19,20",
    "19,21",
    "19,22",
    "19,23",
    "19,24",
    "19,25",
    "19,26",
    "19,27",
    "19,28",
    "19,29",
    "19,30",
    "19,31",
    "20,6",
    "20,7",
    "20,8",
    "20,9",
    "20,10",
    "20,11",
    "20,12",
    "20,13",
    "20,14",
    "20,15",
    "20,16",
    "20,17",
    "20,18",
    "20,22",
    "20,23",
    "20,24",
    "20,25",
    "20,26",
    "20,27",
    "20,28",
    "20,29",
    "20,30",
    "20,31",
    "20,32",
    "21,6",
    "21,7",
    "21,8",
    "21,9",
    "21,10",
    "21,11",
    "21,12",
    "21,13",
    "21,14",
    "21,15",
    "21,16",
    "21,17",
    "21,23",
    "21,24",
    "21,25",
    "21,26",
    "21,27",
    "21,28",
    "21,29",
    "21,30",
    "21,31",
    "21,32",
    "22,6",
    "22,7",
    "22,8",
    "22,9",
    "22,10",
    "22,11",
    "22,12",
    "22,13",
    "22,14",
    "22,15",
    "22,16",
    "22,17",
    "22,24",
    "22,25",
    "22,26",
    "22,27",
    "22,28",
    "22,29",
    "22,30",
    "22,31",
    "22,32",
    "23,6",
    "23,7",
    "23,8",
    "23,9",
    "23,10",
    "23,11",
    "23,12",
    "23,13",
    "23,14",
    "23,15",
    "23,16",
    "23,17",
    "23,26",
    "23,27",
    "23,28",
    "23,29",
    "23,30",
    "23,31",
    "24,6",
    "24,7",
    "24,8",
    "24,9",
    "24,10",
    "24,11",
    "24,12",
    "24,13",
    "24,14",
    "24,15",
    "24,16",
    "24,17",
    "25,6",
    "25,7",
    "25,8",
    "25,9",
    "25,10",
    "25,11",
    "25,12",
    "25,13",
    "25,14",
    "25,15",
    "25,16",
    "25,17",
    "26,6",
    "26,7",
    "26,8",
    "26,9",
    "26,10",
    "26,11",
    "26,12",
    "26,13",
    "26,14",
    "26,15",
    "26,16",
    "26,17",
    "27,6",
    "27,7",
    "27,8",
    "27,9",
    "27,10",
    "27,11",
    "27,12",
    "27,13",
    "27,14",
    "27,15",
    "27,16",
    "28,6",
    "28,7",
    "28,8",
    "28,9",
    "28,10",
    "28,11",
    "28,12",
    "28,13",
    "28,14",
    "29,6",
    "29,7",
    "29,8",
    "29,9",
    "29,10",
    "29,11",
    "29,12",
    "29,13",
    "30,7",
    "30,8",
    "30,9",
    "30,10",
    "30,11",
    "30,12",
    "31,8",
    "31,9",
    "31,10",
    "31,11",
    "34,13",
    "34,14",
    "34,15",
    "35,12",
    "35,13",
    "35,14",
    "35,15",
    "35,16",
    "36,11",
    "36,12",
    "36,13",
    "36,14",
    "36,15",
    "36,16",
    "37,11",
    "37,12",
    "37,13",
    "37,14",
    "37,15",
    "37,16",
    "37,17",
    "38,10",
    "38,11",
    "38,12",
    "38,13",
    "38,14",
    "38,15",
    "38,16",
    "38,17",
    "38,18",
    "38,19",
    "38,20",
    "38,21",
    "38,22",
    "38,23",
    "38,24",
    "38,25",
    "38,26",
    "38,27",
    "39,10",
    "39,11",
    "39,12",
    "39,13",
    "39,14",
    "39,15",
    "39,16",
    "39,17",
    "39,18",
    "39,19",
    "39,20",
    "39,21",
    "39,22",
    "39,23",
    "39,24",
    "39,25",
    "39,26",
    "39,27",
    "39,28",
    "40,10",
    "40,11",
    "40,12",
    "40,13",
    "40,14",
    "40,15",
    "40,16",
    "40,17",
    "40,18",
    "40,19",
    "40,20",
    "40,21",
    "40,22",
    "40,23",
    "40,24",
    "40,25",
    "40,26",
    "40,27",
    "40,28",
    "41,10",
    "41,11",
    "41,12",
    "41,13",
    "41,14",
    "41,15",
    "41,16",
    "41,17",
    "41,18",
    "41,19",
    "41,20",
    "41,21",
    "41,22",
    "41,23",
    "41,24",
    "41,25",
    "41,26",
    "41,27",
    "41,28",
    "42,10",
    "42,11",
    "42,12",
    "42,13",
    "42,14",
    "42,15",
    "42,16",
    "42,17",
    "42,18",
    "42,19",
    "42,20",
    "42,21",
    "42,22",
    "42,23",
    "42,24",
    "42,25",
    "42,26",
    "42,27",
    "43,10",
    "43,11",
    "43,12",
    "43,13",
    "43,14",
    "43,15",
    "43,16",
    "43,17",
    "43,18",
    "43,19",
    "44,10",
    "44,11",
    "44,12",
    "44,13",
    "44,14",
    "44,15",
    "44,16",
    "44,17",
    "44,18",
    "45,11",
    "45,12",
    "45,13"
   ],
   "door": [
    20,
    33
   ],
   "decor": [
    [
     39,
     24,
     "stoneBig"
    ],
    [
     39,
     19,
     "stoneBig"
    ],
    [
     16,
     23,
     "stoneBig"
    ],
    [
     22,
     14,
     "stoneMedium"
    ],
    [
     36,
     16,
     "stoneMedium"
    ],
    [
     39,
     14,
     "stoneMedium"
    ],
    [
     23,
     11,
     "stoneMedium"
    ],
    [
     21,
     17,
     "stoneSmall"
    ],
    [
     18,
     11,
     "stoneSmall"
    ],
    [
     17,
     25,
     "stoneSmall"
    ],
    [
     16,
     15,
     "stoneSmall"
    ],
    [
     42,
     14,
     "stoneSmall"
    ],
    [
     25,
     12,
     "bushMushroom1"
    ],
    [
     18,
     14,
     "bushMushroom1"
    ],
    [
     27,
     6,
     "bushMushroom1"
    ],
    [
     40,
     21,
     "bushMushroom1"
    ],
    [
     25,
     7,
     "bushMushroom2"
    ],
    [
     28,
     10,
     "bushMushroom2"
    ],
    [
     19,
     24,
     "bushMushroom2"
    ],
    [
     18,
     22,
     "bushMushroom2"
    ],
    [
     37,
     14,
     "stoneDecor2"
    ],
    [
     20,
     13,
     "stoneDecor2"
    ],
    [
     15,
     12,
     "stoneDecor2"
    ],
    [
     22,
     28,
     "stoneDecor2"
    ],
    [
     17,
     6,
     "stoneDecor2"
    ],
    [
     25,
     10,
     "stoneDecor3"
    ],
    [
     39,
     12,
     "stoneDecor3"
    ],
    [
     41,
     12,
     "stoneDecor3"
    ],
    [
     41,
     10,
     "stoneDecor3"
    ],
    [
     30,
     10,
     "pcRocks01"
    ],
    [
     35,
     14,
     "pcRocks01"
    ],
    [
     24,
     15,
     "pcRocks05"
    ],
    [
     29,
     12,
     "pcRocks05"
    ],
    [
     37,
     10,
     "bldWallCaveHole"
    ],
    [
     22,
     5,
     "bldWallCaveHole"
    ],
    [
     20,
     5,
     "bldWallCandle"
    ],
    [
     24,
     5,
     "bldWallCandle"
    ],
    [
     42,
     22,
     "bldChest"
    ],
    [
     38,
     22,
     "postLightLit"
    ],
    [
     23,
     31,
     "postLightLit"
    ]
   ],
   "links": {
    "A": {
     "col": 37,
     "row": 11
    }
   },
   "version": "e533d21145",
   "warp": {
    "forwardPortal": [
     {
      "col": 22,
      "row": 6
     }
    ],
    "forwardSpawn": [
     {
      "col": 40,
      "row": 27
     }
    ],
    "returnPortal": [
     {
      "col": 40,
      "row": 28
     }
    ],
    "returnSpawn": [
     {
      "col": 22,
      "row": 7
     }
    ]
   }
  },
  "tunnel_room": {
   "tiles": [
    "7,26",
    "7,27",
    "7,28",
    "7,29",
    "7,30",
    "7,31",
    "8,24",
    "8,25",
    "8,26",
    "8,27",
    "8,28",
    "8,29",
    "8,30",
    "8,31",
    "8,32",
    "9,23",
    "9,24",
    "9,25",
    "9,26",
    "9,27",
    "9,28",
    "9,29",
    "9,30",
    "9,31",
    "9,32",
    "10,22",
    "10,23",
    "10,24",
    "10,25",
    "10,26",
    "10,27",
    "10,28",
    "10,29",
    "10,30",
    "10,31",
    "10,32",
    "11,22",
    "11,23",
    "11,24",
    "11,25",
    "11,26",
    "11,27",
    "11,28",
    "11,29",
    "11,30",
    "11,31",
    "12,21",
    "12,22",
    "12,23",
    "12,24",
    "12,25",
    "12,26",
    "12,27",
    "13,21",
    "13,22",
    "13,23",
    "13,24",
    "13,25",
    "13,26",
    "14,20",
    "14,21",
    "14,22",
    "14,23",
    "14,24",
    "14,25",
    "15,20",
    "15,21",
    "15,22",
    "15,23",
    "15,24",
    "15,25",
    "16,20",
    "16,21",
    "16,22",
    "16,23",
    "16,24",
    "17,20",
    "17,21",
    "17,22",
    "17,23",
    "17,24",
    "18,6",
    "18,7",
    "18,8",
    "18,9",
    "18,20",
    "18,21",
    "18,22",
    "18,23",
    "18,24",
    "19,5",
    "19,6",
    "19,7",
    "19,8",
    "19,9",
    "19,10",
    "19,20",
    "19,21",
    "19,22",
    "19,23",
    "19,24",
    "20,4",
    "20,5",
    "20,6",
    "20,7",
    "20,8",
    "20,9",
    "20,10",
    "20,11",
    "20,20",
    "20,21",
    "20,22",
    "20,23",
    "20,24",
    "21,4",
    "21,5",
    "21,6",
    "21,7",
    "21,8",
    "21,9",
    "21,10",
    "21,11",
    "21,20",
    "21,21",
    "21,22",
    "21,23",
    "21,24",
    "22,5",
    "22,6",
    "22,7",
    "22,8",
    "22,9",
    "22,10",
    "22,11",
    "22,19",
    "22,20",
    "22,21",
    "22,22",
    "22,23",
    "22,24",
    "23,5",
    "23,6",
    "23,7",
    "23,8",
    "23,9",
    "23,10",
    "23,11",
    "23,12",
    "23,19",
    "23,20",
    "23,21",
    "23,22",
    "23,23",
    "23,24",
    "24,5",
    "24,6",
    "24,7",
    "24,8",
    "24,9",
    "24,10",
    "24,11",
    "24,12",
    "24,13",
    "24,18",
    "24,19",
    "24,20",
    "24,21",
    "24,22",
    "24,23",
    "25,5",
    "25,6",
    "25,7",
    "25,8",
    "25,9",
    "25,10",
    "25,11",
    "25,12",
    "25,13",
    "25,14",
    "25,15",
    "25,16",
    "25,17",
    "25,18",
    "25,19",
    "25,20",
    "25,21",
    "25,22",
    "25,23",
    "26,5",
    "26,6",
    "26,7",
    "26,8",
    "26,9",
    "26,10",
    "26,11",
    "26,12",
    "26,13",
    "26,14",
    "26,15",
    "26,16",
    "26,17",
    "26,18",
    "26,19",
    "26,20",
    "26,21",
    "26,22",
    "27,5",
    "27,6",
    "27,7",
    "27,8",
    "27,9",
    "27,10",
    "27,11",
    "27,12",
    "27,13",
    "27,14",
    "27,15",
    "27,16",
    "27,17",
    "27,18",
    "27,19",
    "27,20",
    "27,21",
    "27,22",
    "28,5",
    "28,6",
    "28,7",
    "28,8",
    "28,9",
    "28,10",
    "28,11",
    "28,12",
    "28,13",
    "28,14",
    "28,15",
    "28,16",
    "28,17",
    "28,18",
    "28,19",
    "28,20",
    "28,21",
    "29,5",
    "29,6",
    "29,7",
    "29,8",
    "29,9",
    "29,10",
    "29,11",
    "29,12",
    "29,13",
    "29,14",
    "29,15",
    "29,16",
    "29,17",
    "29,18",
    "29,19",
    "29,20",
    "30,6",
    "30,7",
    "30,8",
    "30,9",
    "30,10",
    "30,13",
    "30,14",
    "30,15",
    "30,16",
    "30,17",
    "30,18",
    "30,19",
    "31,7",
    "31,8",
    "31,9",
    "38,17",
    "38,18",
    "38,19",
    "38,20",
    "38,21",
    "38,22",
    "39,15",
    "39,16",
    "39,17",
    "39,18",
    "39,19",
    "39,20",
    "39,21",
    "39,22",
    "39,23",
    "40,14",
    "40,15",
    "40,16",
    "40,17",
    "40,18",
    "40,19",
    "40,20",
    "40,21",
    "40,22",
    "40,23",
    "40,24",
    "41,14",
    "41,15",
    "41,16",
    "41,17",
    "41,18",
    "41,19",
    "41,20",
    "41,21",
    "41,22",
    "41,23",
    "41,24",
    "41,25",
    "42,14",
    "42,15",
    "42,16",
    "42,17",
    "42,18",
    "42,19",
    "42,20",
    "42,21",
    "42,22",
    "42,23",
    "42,24",
    "42,25",
    "42,26",
    "42,27",
    "42,28",
    "42,29",
    "42,30",
    "42,31",
    "43,15",
    "43,16",
    "43,17",
    "43,18",
    "43,19",
    "43,20",
    "43,21",
    "43,22",
    "43,23",
    "43,24",
    "43,25",
    "43,26",
    "43,27",
    "43,28",
    "43,29",
    "43,30",
    "43,31",
    "43,32",
    "44,15",
    "44,16",
    "44,17",
    "44,18",
    "44,19",
    "44,20",
    "44,21",
    "44,22",
    "44,23",
    "44,24",
    "44,25",
    "44,26",
    "44,27",
    "44,28",
    "44,29",
    "44,30",
    "44,31",
    "44,32",
    "45,15",
    "45,16",
    "45,17",
    "45,18",
    "45,19",
    "45,20",
    "45,21",
    "45,22",
    "45,23",
    "45,24",
    "45,25",
    "45,26",
    "45,27",
    "45,28",
    "45,29",
    "45,30",
    "45,31",
    "45,32",
    "46,15",
    "46,16",
    "46,17",
    "46,18",
    "46,19",
    "46,20",
    "46,21",
    "46,22",
    "46,23",
    "46,24",
    "46,25",
    "46,26",
    "46,27",
    "46,28",
    "46,29",
    "46,30",
    "46,31",
    "47,15",
    "47,16",
    "47,17",
    "47,18",
    "47,19",
    "47,20",
    "47,21",
    "47,22",
    "47,23",
    "47,24",
    "48,16",
    "48,17",
    "48,18",
    "48,19",
    "48,20",
    "48,21",
    "48,22",
    "48,23",
    "49,16",
    "49,17",
    "49,18",
    "49,19",
    "49,20",
    "49,21",
    "49,22",
    "49,23",
    "50,17",
    "50,18",
    "50,19",
    "50,20",
    "50,21",
    "50,22",
    "50,23",
    "51,18",
    "51,19",
    "51,20",
    "51,21",
    "51,22"
   ],
   "door": [
    8,
    33
   ],
   "decor": [
    [
     25,
     21,
     "stoneBig"
    ],
    [
     23,
     21,
     "stoneBig"
    ],
    [
     40,
     21,
     "stoneBig"
    ],
    [
     44,
     17,
     "stoneMedium"
    ],
    [
     12,
     22,
     "stoneMedium"
    ],
    [
     16,
     24,
     "stoneMedium"
    ],
    [
     42,
     23,
     "stoneMedium"
    ],
    [
     26,
     13,
     "stoneSmall"
    ],
    [
     44,
     25,
     "stoneSmall"
    ],
    [
     14,
     23,
     "stoneSmall"
    ],
    [
     24,
     8,
     "stoneSmall"
    ],
    [
     49,
     21,
     "stoneSmall"
    ],
    [
     20,
     24,
     "bushMushroom1"
    ],
    [
     26,
     18,
     "bushMushroom1"
    ],
    [
     27,
     7,
     "bushMushroom1"
    ],
    [
     43,
     19,
     "bushMushroom1"
    ],
    [
     21,
     6,
     "bushMushroom2"
    ],
    [
     27,
     21,
     "bushMushroom2"
    ],
    [
     22,
     10,
     "bushMushroom2"
    ],
    [
     19,
     20,
     "bushMushroom2"
    ],
    [
     45,
     28,
     "stoneDecor2"
    ],
    [
     20,
     8,
     "stoneDecor2"
    ],
    [
     21,
     20,
     "stoneDecor2"
    ],
    [
     30,
     8,
     "stoneDecor2"
    ],
    [
     29,
     19,
     "stoneDecor2"
    ],
    [
     47,
     21,
     "stoneDecor3"
    ],
    [
     18,
     23,
     "stoneDecor3"
    ],
    [
     40,
     19,
     "stoneDecor3"
    ],
    [
     43,
     21,
     "stoneDecor3"
    ],
    [
     28,
     11,
     "pcRocks01"
    ],
    [
     45,
     22,
     "pcRocks01"
    ],
    [
     50,
     18,
     "pcRocks05"
    ],
    [
     10,
     24,
     "pcRocks05"
    ],
    [
     41,
     13,
     "bldWallCaveHole"
    ],
    [
     47,
     14,
     "bldWallCaveHole"
    ],
    [
     24,
     4,
     "bldWallCaveHole"
    ],
    [
     22,
     4,
     "bldWallCandle"
    ],
    [
     26,
     4,
     "bldWallCandle"
    ],
    [
     46,
     26,
     "bldChest"
    ],
    [
     42,
     26,
     "postLightLit"
    ],
    [
     11,
     31,
     "postLightLit"
    ]
   ],
   "links": {
    "A": {
     "col": 41,
     "row": 14
    },
    "B": {
     "col": 47,
     "row": 15
    }
   },
   "version": "d6701a8879",
   "warp": {
    "forwardPortal": [
     {
      "col": 24,
      "row": 5
     }
    ],
    "forwardSpawn": [
     {
      "col": 44,
      "row": 31
     }
    ],
    "returnPortal": [
     {
      "col": 44,
      "row": 32
     }
    ],
    "returnSpawn": [
     {
      "col": 24,
      "row": 6
     }
    ]
   }
  },
  "cave2_room": {
   "tiles": [
    "2,17",
    "2,18",
    "2,19",
    "3,16",
    "3,17",
    "3,18",
    "3,19",
    "3,20",
    "4,16",
    "4,17",
    "4,18",
    "4,19",
    "4,20",
    "4,21",
    "5,16",
    "5,17",
    "5,18",
    "5,19",
    "5,20",
    "5,21",
    "5,22",
    "6,15",
    "6,16",
    "6,17",
    "6,18",
    "6,19",
    "6,20",
    "6,21",
    "6,22",
    "6,23",
    "6,24",
    "6,25",
    "6,26",
    "6,27",
    "6,28",
    "6,29",
    "6,30",
    "6,31",
    "7,15",
    "7,16",
    "7,17",
    "7,18",
    "7,19",
    "7,20",
    "7,21",
    "7,22",
    "7,23",
    "7,24",
    "7,25",
    "7,26",
    "7,27",
    "7,28",
    "7,29",
    "7,30",
    "7,31",
    "7,32",
    "8,15",
    "8,16",
    "8,17",
    "8,18",
    "8,19",
    "8,20",
    "8,21",
    "8,22",
    "8,23",
    "8,24",
    "8,25",
    "8,26",
    "8,27",
    "8,28",
    "8,29",
    "8,30",
    "8,31",
    "8,32",
    "9,15",
    "9,16",
    "9,17",
    "9,18",
    "9,19",
    "9,20",
    "9,21",
    "9,22",
    "9,23",
    "9,24",
    "9,25",
    "9,26",
    "9,27",
    "9,28",
    "9,29",
    "9,30",
    "9,31",
    "9,32",
    "10,15",
    "10,16",
    "10,17",
    "10,18",
    "10,19",
    "10,20",
    "10,21",
    "10,22",
    "10,23",
    "10,24",
    "10,25",
    "10,26",
    "10,27",
    "10,28",
    "10,29",
    "10,30",
    "10,31",
    "11,15",
    "11,16",
    "11,17",
    "11,18",
    "11,19",
    "11,20",
    "11,21",
    "11,22",
    "11,23",
    "11,24",
    "12,15",
    "12,16",
    "12,17",
    "12,18",
    "12,19",
    "12,20",
    "12,21",
    "12,22",
    "12,23",
    "13,16",
    "13,17",
    "13,18",
    "13,19",
    "16,9",
    "16,10",
    "16,11",
    "17,8",
    "17,9",
    "17,10",
    "17,11",
    "17,12",
    "18,7",
    "18,8",
    "18,9",
    "18,10",
    "18,11",
    "18,12",
    "18,13",
    "19,6",
    "19,7",
    "19,8",
    "19,9",
    "19,10",
    "19,11",
    "19,12",
    "19,13",
    "19,14",
    "20,6",
    "20,7",
    "20,8",
    "20,9",
    "20,10",
    "20,11",
    "20,12",
    "20,13",
    "20,14",
    "20,15",
    "21,5",
    "21,6",
    "21,7",
    "21,8",
    "21,9",
    "21,10",
    "21,11",
    "21,12",
    "21,13",
    "21,14",
    "21,15",
    "22,5",
    "22,6",
    "22,7",
    "22,8",
    "22,9",
    "22,10",
    "22,11",
    "22,12",
    "22,13",
    "22,14",
    "22,15",
    "23,5",
    "23,6",
    "23,7",
    "23,8",
    "23,9",
    "23,10",
    "23,11",
    "23,12",
    "23,13",
    "23,14",
    "23,15",
    "24,5",
    "24,6",
    "24,7",
    "24,8",
    "24,9",
    "24,10",
    "24,11",
    "24,12",
    "24,13",
    "24,14",
    "25,6",
    "25,7",
    "25,8",
    "25,9",
    "25,10",
    "25,11",
    "25,12",
    "25,13",
    "25,14",
    "25,27",
    "25,28",
    "25,29",
    "25,30",
    "25,31",
    "26,6",
    "26,7",
    "26,8",
    "26,9",
    "26,10",
    "26,11",
    "26,12",
    "26,13",
    "26,14",
    "26,15",
    "26,25",
    "26,26",
    "26,27",
    "26,28",
    "26,29",
    "26,30",
    "26,31",
    "26,32",
    "27,6",
    "27,7",
    "27,8",
    "27,9",
    "27,10",
    "27,11",
    "27,12",
    "27,13",
    "27,14",
    "27,15",
    "27,16",
    "27,24",
    "27,25",
    "27,26",
    "27,27",
    "27,28",
    "27,29",
    "27,30",
    "27,31",
    "27,32",
    "28,6",
    "28,7",
    "28,8",
    "28,9",
    "28,10",
    "28,11",
    "28,12",
    "28,13",
    "28,14",
    "28,15",
    "28,16",
    "28,17",
    "28,24",
    "28,25",
    "28,26",
    "28,27",
    "28,28",
    "28,29",
    "28,30",
    "28,31",
    "28,32",
    "29,6",
    "29,7",
    "29,8",
    "29,9",
    "29,10",
    "29,11",
    "29,12",
    "29,13",
    "29,14",
    "29,15",
    "29,16",
    "29,17",
    "29,18",
    "29,23",
    "29,24",
    "29,25",
    "29,26",
    "29,27",
    "29,28",
    "29,29",
    "29,30",
    "29,31",
    "30,7",
    "30,8",
    "30,9",
    "30,10",
    "30,11",
    "30,12",
    "30,13",
    "30,14",
    "30,15",
    "30,16",
    "30,17",
    "30,18",
    "30,19",
    "30,22",
    "30,23",
    "30,24",
    "30,25",
    "30,26",
    "30,27",
    "30,28",
    "31,7",
    "31,8",
    "31,9",
    "31,10",
    "31,11",
    "31,12",
    "31,13",
    "31,14",
    "31,15",
    "31,16",
    "31,17",
    "31,18",
    "31,19",
    "31,20",
    "31,21",
    "31,22",
    "31,23",
    "31,24",
    "31,25",
    "31,26",
    "31,27",
    "32,8",
    "32,9",
    "32,10",
    "32,11",
    "32,12",
    "32,13",
    "32,14",
    "32,15",
    "32,16",
    "32,17",
    "32,18",
    "32,19",
    "32,20",
    "32,21",
    "32,22",
    "32,23",
    "32,24",
    "32,25",
    "32,26",
    "32,27",
    "33,9",
    "33,10",
    "33,11",
    "33,15",
    "33,16",
    "33,17",
    "33,18",
    "33,19",
    "33,20",
    "33,21",
    "33,22",
    "33,23",
    "33,24",
    "33,25",
    "33,26",
    "34,16",
    "34,17",
    "34,18",
    "34,19",
    "34,20",
    "34,21",
    "34,22",
    "34,23",
    "34,24",
    "34,25",
    "35,17",
    "35,18",
    "35,19",
    "35,20",
    "35,21",
    "35,22",
    "35,23",
    "35,24"
   ],
   "door": [
    26,
    33
   ],
   "decor": [
    [
     21,
     6,
     "stoneBig"
    ],
    [
     4,
     20,
     "stoneBig"
    ],
    [
     25,
     10,
     "stoneBig"
    ],
    [
     19,
     8,
     "stoneMedium"
    ],
    [
     28,
     14,
     "stoneMedium"
    ],
    [
     7,
     20,
     "stoneMedium"
    ],
    [
     22,
     9,
     "stoneMedium"
    ],
    [
     9,
     20,
     "stoneSmall"
    ],
    [
     30,
     8,
     "stoneSmall"
    ],
    [
     28,
     12,
     "stoneSmall"
    ],
    [
     24,
     12,
     "stoneSmall"
    ],
    [
     27,
     7,
     "stoneSmall"
    ],
    [
     22,
     14,
     "bushMushroom1"
    ],
    [
     6,
     22,
     "bushMushroom1"
    ],
    [
     30,
     24,
     "bushMushroom1"
    ],
    [
     11,
     18,
     "bushMushroom1"
    ],
    [
     34,
     18,
     "bushMushroom2"
    ],
    [
     20,
     14,
     "bushMushroom2"
    ],
    [
     29,
     10,
     "bushMushroom2"
    ],
    [
     28,
     25,
     "bushMushroom2"
    ],
    [
     11,
     21,
     "stoneDecor2"
    ],
    [
     32,
     11,
     "stoneDecor2"
    ],
    [
     9,
     22,
     "stoneDecor2"
    ],
    [
     29,
     16,
     "stoneDecor2"
    ],
    [
     7,
     28,
     "stoneDecor2"
    ],
    [
     33,
     16,
     "stoneDecor3"
    ],
    [
     17,
     9,
     "stoneDecor3"
    ],
    [
     31,
     14,
     "stoneDecor3"
    ],
    [
     33,
     25,
     "stoneDecor3"
    ],
    [
     22,
     12,
     "pcRocks01"
    ],
    [
     9,
     27,
     "pcRocks01"
    ],
    [
     8,
     24,
     "pcRocks05"
    ],
    [
     34,
     22,
     "pcRocks05"
    ],
    [
     5,
     15,
     "bldWallCaveHole"
    ],
    [
     24,
     4,
     "bldWallCaveHole"
    ],
    [
     22,
     4,
     "bldWallCandle"
    ],
    [
     26,
     4,
     "bldWallCandle"
    ],
    [
     10,
     26,
     "bldChest"
    ],
    [
     6,
     26,
     "postLightLit"
    ],
    [
     29,
     31,
     "postLightLit"
    ]
   ],
   "links": {
    "A": {
     "col": 5,
     "row": 16
    }
   },
   "version": "147a606572",
   "warp": {
    "forwardPortal": [
     {
      "col": 24,
      "row": 5
     }
    ],
    "forwardSpawn": [
     {
      "col": 8,
      "row": 31
     }
    ],
    "returnPortal": [
     {
      "col": 8,
      "row": 32
     }
    ],
    "returnSpawn": [
     {
      "col": 24,
      "row": 6
     }
    ]
   }
  }
 },
 "version": "20261005hw"
};
